name: Flag PR for cherry-pick
on:
  issue_comment:
    types: [created]
jobs:
  add-cherry-pick-label:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/cherry-pick')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['cherry-pick-required']
            });
