name: Flag PR for cherry-pick

on:
  issue_comment:
    types: [created]

jobs:
  add-cherry-pick-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Extract Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: "cherry-pick"
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write
      - name: Add label to PR
        uses: christianvuerings/add-labels@v1
        with:
          labels: |
            cherry-pick-required
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
