# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Issue and PR comment commands

permissions: {}

on:
  issue_comment:
    types: 
      - created
      - edited

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@c44ac3a57d67639e39e4a4988b52049ef45b80dd # v2.0.0
        with:
          prow-commands: '/assign 
            /unassign
            /lgtm 
            /milestone'
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  cherry-pick:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/cherry-pick')
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check if PR is merged
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: check-merged
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              merged: pr.data.merged,
              mergeCommit: pr.data.merge_commit_sha
            };

      - name: Extract target branch
        if: fromJSON(steps.check-merged.outputs.result).merged == true
        id: extract-branch
        run: echo "branch=$(echo '${{ github.event.comment.body }}' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Checkout repository
        if: fromJSON(steps.check-merged.outputs.result).merged == true
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Cherry Pick
        if: fromJSON(steps.check-merged.outputs.result).merged == true
        uses: ./.github/actions/cherry-pick
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source-pr: ${{ github.event.issue.number }}
          target-branches: ${{ steps.extract-branch.outputs.branch }}
          merge-commit: ${{ fromJson(steps.check-merged.outputs.result).mergeCommit }}

